# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a272c12b3483053690bd195908e12550ba161be5caa1aca7479c4070df402e8271208e6fc4f08c5c885a2a6045f28c0dfbc52472c5f682d0877855adbdd898

test:
  secret_key_base: 25483f06c87c0b25280e7c7a90df05e3e39410edcd232035298971c6e61a83df1ae75f647f4d74c69090e7e8207467eff3eea4ef7ed5e05c3bf8678a5ec58926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
